# This file was generated by GoReleaser. DO NOT EDIT.
cask "memo" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "5a249aa9806611bfb2041b39bcb913e378230300fb09d2e10034607137fec410"
      url "https://github.com/jcyamacho/memo/releases/download/v#{version}/memo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4c32311ca499625b67a2d4b9fc37053c06933ba879bd642badd7bbf8341bdefe"
      url "https://github.com/jcyamacho/memo/releases/download/v#{version}/memo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4c357a6f63a1653d3e70cc7ed3aa3615761a6f7d7e1abacd7e91f314fbbb0ae1"
      url "https://github.com/jcyamacho/memo/releases/download/v#{version}/memo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6e890a5725e7afc3c32d3bcd919327513c4b9d3d96f68755dd0e223ec5772068"
      url "https://github.com/jcyamacho/memo/releases/download/v#{version}/memo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "memo"
  desc "Durable memory CLI for humans and coding agents"
  homepage "https://github.com/jcyamacho/memo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "memo"

  # No zap stanza required

end
