# This file was generated by GoReleaser. DO NOT EDIT.
cask "memo" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "19ea899f15f8aede6ac65c88b104bc60eb416ad39bf1ccc5090974d6d8ba15d3"
      url "https://github.com/jcyamacho/memo/releases/download/v#{version}/memo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8106082722515ea62a66dbcd881cfbbc3f116a26e8a4c59a40d16e5d92d430d4"
      url "https://github.com/jcyamacho/memo/releases/download/v#{version}/memo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "619f1247e0615d823a57b756536d24ba10f74e10e1a7c9999db1314cc0e0b392"
      url "https://github.com/jcyamacho/memo/releases/download/v#{version}/memo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e20cb13ee4d77530c571b1d5772d0ef583af49e192e702cb77c41dcb4388a6cc"
      url "https://github.com/jcyamacho/memo/releases/download/v#{version}/memo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "memo"
  desc "Durable memory CLI for humans and coding agents"
  homepage "https://github.com/jcyamacho/memo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "memo"

  # No zap stanza required

end
