# This file was generated by GoReleaser. DO NOT EDIT.
cask "memo" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "4552e549e40ef8919ec057503922e249954aa919bb84f40d7e501dbcc9f77d29"
      url "https://github.com/jcyamacho/memo/releases/download/v#{version}/memo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fee761af285c5ae644989c5ecd5a171f933e6e5ca4db92da15034a142f0e9f0b"
      url "https://github.com/jcyamacho/memo/releases/download/v#{version}/memo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "381a874deaa8ed5a4e73ef0720c7985a912a696d688629e82f5c0a5afca6762d"
      url "https://github.com/jcyamacho/memo/releases/download/v#{version}/memo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "90ca89f87ce91af553e992fe55be5b8958be797390ee43f92283637226019122"
      url "https://github.com/jcyamacho/memo/releases/download/v#{version}/memo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "memo"
  desc "Durable memory CLI for humans and coding agents"
  homepage "https://github.com/jcyamacho/memo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "memo"

  # No zap stanza required

end
